version: '3'
services:
  app:
    container_name: ${APP_NAME}_app
    image: tommypria:php8.1.0
    volumes:
      - ../../src:/var/www/html
      - ../config/php/config.ini:/usr/local/etc/php/conf.d/config.ini
    networks:
      - backend

  web:
    container_name: ${APP_NAME}_web
    image: nginx:alpine
    ports:
      - ${DOCKER_WEB_PORT}:80
      - "443:443"
    volumes:
      - ../../src:/var/www/html
      - ../config/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - backend
    depends_on:
      - app

  db:
    container_name: ${APP_NAME}_db
    image: mysql:5.7.22
    tty: true
    env_file:
      - db.env
    ports:
      - ${DOCKER_MYSQL_PORT}:3306
    volumes:
      - ./../data/mysql:/var/lib/mysql/
      - ./../config/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - backend
    restart: unless-stopped

  redis:
    container_name: ${APP_NAME}_redis
    image: redis:alpine
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    volumes:
      - ../data/redis:/data
    ports:
      - ${DOCKER_REDIS_PORT}:6379
    networks:
      - backend
    depends_on:
      - app

networks:
  backend:
    driver: "bridge"
